version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-lol_bot}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped
    container_name: postgres
    networks:
      - lol-bot-network

  discord-bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RIOT_API_KEY=${RIOT_API_KEY}
      - MONITOR_CHANNEL_ID=${MONITOR_CHANNEL_ID}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-lol_bot}
    restart: unless-stopped
    container_name: discord-bot
    networks:
      - lol-bot-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  lol-bot-network:
    external: true
